---
nagios_version: '4.4.5'
nagios_plugin_version: '2.2.1'
packages:
  - autoconf
  - gcc
  - glibc 
  - glibc-common
  - wget 
  - unzip 
  - httpd 
  - php 
  - gd 
  - gd-devel
  - perl 
  - postfix
  - make
  - gettext
  - automake
  - autoconf
  - openssl-devel
  - net-snmp
  - net-snmp-utils
  - epel-release
  - perl-Net-SNMP
nagios_code_location: /tmp/nagioscore.tar.gz
username: apache
apache_package: httpd
compile: ./configure
apache_config_files: make install-webconf > webconf.log
nagios_plugin_location: /tmp/nagios-plugins.tar.gz


