---
nagios_version: '4.4.5'
nagios_plugin_version: '2.2.1'
packages:
  - autoconf 
  - gcc 
  - libc6 
  - make 
  - wget 
  - unzip 
  - apache2 
  - php 
  - libapache2-mod-php7.2 
  - libgd-dev
  - libmcrypt-dev 
  - libssl-dev 
  - bc 
  - gawk 
  - dc 
  - build-essential 
  - snmp 
  - libnet-snmp-perl 
  - gettext
  - python-pip
nagios_code_location: /tmp/nagioscore.tar.gz
nagios_plugin_location: /tmp/nagios-plugins.tar.gz
username: www-data
apache_package: apache2
compile: sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
apache_config_files: sudo make install-webconf > webconf.log  && sudo a2enmod rewrite > a2enmodrewrite.log && sudo a2enmod cgi > cgi.log
